<a id="start"></a>

<span style="padding: 0 05px"></span> [ <font color = "black" size ="3.5" > **Ch 1.** <span style = "padding:0 2px"></span> **Data Processing**](#ch_1) </font>   <br/>
<span style="padding: 0 40px"></span> [ <font color = "blue" size ="2" > 1.1 <span style = "padding:0 12px"></span> import mostly used libraries](#ref_1.1) </font>   <br/>
<span style="padding: 0 40px"></span> [ <font color = "blue" size ="2" > 1.2 <span style = "padding:0 12px"></span> import data frame and have a look on missing values](#ref_1.2) </font>   <br/>
<span style="padding: 0 40px"></span> [ <font color = "blue" size ="2" > 1.3 <span style = "padding:0 12px"></span> import sklearn for filling gaps](#ref_1.3) </font>   <br/>
<span style="padding: 0 40px"></span> [ <font color = "blue" size ="2" > 1.4 <span style = "padding:0 12px"></span> Splitting into test and training sets](#ref_1.4) </font>   <br/>


### Ch 1. Data Processing <a id="ch_1"></a>

#### <font color = "navy" >1.1) import mostly used libraries </font> <a id="ref_1.1"></a>

In [10]:
%reset -f
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

[Back to Top](#start)

#### <font color = "navy" >1.2) import data frame and have a look on missing values</font> <a id="ref_1.2"></a>

In [11]:
df = pd.read_csv("Data.csv")
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

<font color = "Brown" size ="4" >  
df.Country => dummy variables  <br/>
df.Purchased => categorical data <br>    
</font>

- **<font color = 'blue' > for df.Purchased columns</font>**

In [12]:
print(df.Purchased)   # look at the dtype

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object


In [13]:
df.Purchased = pd.Categorical(df.Purchased,categories=["No","Yes"])

In [14]:
print(df.Purchased)   # look at the dtype

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: category
Categories (2, object): [No, Yes]


In [15]:
df.Purchased = df.Purchased.cat.codes

In [16]:
df

Country   Age   Salary  Purchased
0   France  44.0  72000.0          0
1    Spain  27.0  48000.0          1
2  Germany  30.0  54000.0          0
3    Spain  38.0  61000.0          0
4  Germany  40.0      NaN          1
5   France  35.0  58000.0          1
6    Spain   NaN  52000.0          0
7   France  48.0  79000.0          1
8  Germany  50.0  83000.0          0
9   France  37.0  67000.0          1

In [17]:
print(df.Purchased)   # look at the dtype

0    0
1    1
2    0
3    0
4    1
5    1
6    0
7    1
8    0
9    1
Name: Purchased, dtype: int8


- **<font color = 'blue' > for df.Country column</font>**

In [18]:
df

Country   Age   Salary  Purchased
0   France  44.0  72000.0          0
1    Spain  27.0  48000.0          1
2  Germany  30.0  54000.0          0
3    Spain  38.0  61000.0          0
4  Germany  40.0      NaN          1
5   France  35.0  58000.0          1
6    Spain   NaN  52000.0          0
7   France  48.0  79000.0          1
8  Germany  50.0  83000.0          0
9   France  37.0  67000.0          1

In [19]:
tmp = pd.get_dummies(df)
tmp

Age   Salary  Purchased  Country_France  Country_Germany  Country_Spain
0  44.0  72000.0          0               1                0              0
1  27.0  48000.0          1               0                0              1
2  30.0  54000.0          0               0                1              0
3  38.0  61000.0          0               0                0              1
4  40.0      NaN          1               0                1              0
5  35.0  58000.0          1               1                0              0
6   NaN  52000.0          0               0                0              1
7  48.0  79000.0          1               1                0              0
8  50.0  83000.0          0               0                1              0
9  37.0  67000.0          1               1                0              0

In [20]:
df = tmp.iloc[:,[3,4,5,0,1,2]]
df

Country_France  Country_Germany  Country_Spain   Age   Salary  Purchased
0               1                0              0  44.0  72000.0          0
1               0                0              1  27.0  48000.0          1
2               0                1              0  30.0  54000.0          0
3               0                0              1  38.0  61000.0          0
4               0                1              0  40.0      NaN          1
5               1                0              0  35.0  58000.0          1
6               0                0              1   NaN  52000.0          0
7               1                0              0  48.0  79000.0          1
8               0                1              0  50.0  83000.0          0
9               1                0              0  37.0  67000.0          1

<font color = "Brown" size ="4" >  
 divide into dependent(X) and independent variables(Y)  , **ONLY VALUES**  <br/>
</font>

In [21]:
X = df.iloc[:, :-1].values
y = df.iloc[:,5].values

In [22]:
X
# y

array([[1.0e+00, 0.0e+00, 0.0e+00, 4.4e+01, 7.2e+04],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.7e+01, 4.8e+04],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.0e+01, 5.4e+04],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.8e+01, 6.1e+04],
       [0.0e+00, 1.0e+00, 0.0e+00, 4.0e+01,     nan],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.5e+01, 5.8e+04],
       [0.0e+00, 0.0e+00, 1.0e+00,     nan, 5.2e+04],
       [1.0e+00, 0.0e+00, 0.0e+00, 4.8e+01, 7.9e+04],
       [0.0e+00, 1.0e+00, 0.0e+00, 5.0e+01, 8.3e+04],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.7e+01, 6.7e+04]])

#### <font color = "navy" >1.3) import sklearn AND filling gaps</font> <a id="ref_1.3"></a>

In [23]:
from sklearn.impute import SimpleImputer

- **<font color = 'blue' >Step-1 make an object of this 'SimpleImputer tag'</font>**

In [24]:
imputer = SimpleImputer(missing_values=np.nan,strategy="mean")

- **<font color = 'blue' > Step-2 apply imputerrrrr.fit() function to our X[:,numeric_cols] variable</font>**

In [25]:
imputer = imputer.fit(X[:,3:5])

- **<font color = 'blue' > Step-3 tranform the missing data via "transform function"</font>**

In [26]:
X[:,3:5] = imputer.transform(X[:,3:5])

In [27]:
np.around(X,0)

array([[1.0000e+00, 0.0000e+00, 0.0000e+00, 4.4000e+01, 7.2000e+04],
       [0.0000e+00, 0.0000e+00, 1.0000e+00, 2.7000e+01, 4.8000e+04],
       [0.0000e+00, 1.0000e+00, 0.0000e+00, 3.0000e+01, 5.4000e+04],
       [0.0000e+00, 0.0000e+00, 1.0000e+00, 3.8000e+01, 6.1000e+04],
       [0.0000e+00, 1.0000e+00, 0.0000e+00, 4.0000e+01, 6.3778e+04],
       [1.0000e+00, 0.0000e+00, 0.0000e+00, 3.5000e+01, 5.8000e+04],
       [0.0000e+00, 0.0000e+00, 1.0000e+00, 3.9000e+01, 5.2000e+04],
       [1.0000e+00, 0.0000e+00, 0.0000e+00, 4.8000e+01, 7.9000e+04],
       [0.0000e+00, 1.0000e+00, 0.0000e+00, 5.0000e+01, 8.3000e+04],
       [1.0000e+00, 0.0000e+00, 0.0000e+00, 3.7000e+01, 6.7000e+04]])

[Back to Top](#start)

#### <font color = "navy" >1.4) Splitting into test and training sets</font> <a id="ref_1.4"></a>

In [28]:
from sklearn.model_selection import train_test_split

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20, random_state=0)

<font color = "Brown" size ="4" >  
 Have a look on each variable  <br/>
</font>

In [30]:
# X_train
print(np.array_str(X_train,precision=3,suppress_small=True))

[[    0.        1.        0.       40.    63777.778]
 [    1.        0.        0.       37.    67000.   ]
 [    0.        0.        1.       27.    48000.   ]
 [    0.        0.        1.       38.778 52000.   ]
 [    1.        0.        0.       48.    79000.   ]
 [    0.        0.        1.       38.    61000.   ]
 [    1.        0.        0.       44.    72000.   ]
 [    1.        0.        0.       35.    58000.   ]]


In [31]:
# X_test
print(np.array_str(X_test,precision =3, suppress_small = True))

[[    0.     1.     0.    30. 54000.]
 [    0.     1.     0.    50. 83000.]]


In [32]:
y_train

array([1, 1, 1, 0, 1, 0, 0, 1], dtype=int8)

In [33]:
y_test

array([0, 0], dtype=int8)

[Back to Top](#start)

#### <font color = "navy" >1.5) Feature scalling</font> <a id="ref_1.5"></a>

In [34]:
from sklearn.preprocessing import StandardScaler

In [35]:
se_X = StandardScaler()

In [36]:
X_train = se_X.fit_transform(X_train)

In [37]:
X_test = se_X.transform(X_test)

In [38]:
X_train

array([[-1.        ,  2.64575131, -0.77459667,  0.26306757,  0.12381479],
       [ 1.        , -0.37796447, -0.77459667, -0.25350148,  0.46175632],
       [-1.        , -0.37796447,  1.29099445, -1.97539832, -1.53093341],
       [-1.        , -0.37796447,  1.29099445,  0.05261351, -1.11141978],
       [ 1.        , -0.37796447, -0.77459667,  1.64058505,  1.7202972 ],
       [-1.        , -0.37796447,  1.29099445, -0.0813118 , -0.16751412],
       [ 1.        , -0.37796447, -0.77459667,  0.95182631,  0.98614835],
       [ 1.        , -0.37796447, -0.77459667, -0.59788085, -0.48214934]])

In [39]:
X_test

array([[-1.        ,  2.64575131, -0.77459667, -1.45882927, -0.90166297],
       [-1.        ,  2.64575131, -0.77459667,  1.98496442,  2.13981082]])

[Back to Top](#start)